
services:

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kerberos
    container_name: kafka_kraft
    hostname: kraftkafka-poc
    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:SASL_SSL,LISTENER:SASL_SSL'
      KAFKA_LISTENERS: 'LISTENER://:9092,CONTROLLER://:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER'
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_SASL_MECHANISMS: GSSAPI
      KAFKA_SASL_ENABLED_MECHANISM: kafka
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf -Djava.security.krb5.conf=/etc/kafka/secrets/krb5.conf
    volumes:
      - ./configs/secrets:/etc/kafka/secrets
    networks:
      - altinity_default

  kerberos:
    container_name: kdc_server
    hostname: kdc-server
    image: altinity/kdc-server
    volumes:
      - /dev/urandom:/dev/random
      - ./configs/secrets:/tmp/secrets
    ports:
      - "749:749"
      -  "88:88/udp"
    networks:
      - altinity_default

networks:
  altinity_default:
