services:

  kerberos:
    container_name: kdc-server
    hostname: kdc-server
    image: altinity/kdc-server:latest
    volumes:
      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - /dev/urandom:/dev/random
      - ./configs/secrets:/tmp/secrets
    ports:
      - "749:749"
      - "88:88/udp"
    networks:
      - altinity_default

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: cp-zookeeper
    hostname: cp-zookeeper
    depends_on:
      - kerberos
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_AUTHPROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/zookeeper/secrets/zookeeper_jaas.conf -Djava.security.krb5.conf=/etc/zookeeper/secrets/krb5.conf
    ports:
      - "2181:2181"
    volumes:
      - ./configs/secrets:/etc/zookeeper/secrets
    networks:
      - altinity_default

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: cp-kafka
    hostname: cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: cp-zookeeper:2181
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka
      # https://docs.confluent.io/platform/current/kafka/multi-node.html#configure-multi-node-environment
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://cp-kafka:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT, LISTENER_EXTERNAL:SASL_PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf -Djava.security.krb5.conf=/etc/kafka/secrets/krb5.conf
    volumes:
      - ./configs/secrets:/etc/kafka/secrets
    networks:
      - altinity_default




networks:
  altinity_default:
    external: true